#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export HOME=/root
export TERM=linux


echo "0 0 0 0" > /proc/sys/kernel/printk 2>/dev/null

mount -t proc proc /proc 2>/dev/null
mount -t sysfs sysfs /sys 2>/dev/null
mount -t devtmpfs dev /dev 2>/dev/null

mkdir -p /dev/pts /tmp /run
mount -t devpts devpts /dev/pts 2>/dev/null


if [ -f /etc/profile ]; then
    . /etc/profile
fi


clear


if [ -x /bin/toucanfetch ]; then
    /bin/toucanfetch
    echo ""
fi


cd /root 2>/dev/null || cd /


while true; do
    /bin/sh -l
done
